default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: books_api_development

test:
  <<: *default
  database: books_api_test


production:
  <<: *default
  database: books_api_production
  username: books_api
  password: <%= ENV['BOOKS_API_DATABASE_PASSWORD'] %>
